apiVersion: "v1"
kind: "LimitRange"
metadata:
  name: "core-resource-limits"
spec:
  limits:
    - type: "Pod"
      max:
        cpu: "0.2"
        memory: "1Gi"
      min:
        cpu: "50m"
        memory: "6Mi"
    - type: "Container"
      max:
        cpu: "2"
        memory: "1Gi"
      min:
        cpu: "50m"
        memory: "4Mi"
      default:
        cpu: "50m"
        memory: "200Mi"
      defaultRequest:
        cpu: "50m"
        memory: "100Mi"
      maxLimitRequestRatio:
        cpu: "10"